import = [
  # uncomment the flavour you want below:
  # "~/.config/alacritty/catppuccin-latte.toml"
  # "~/.config/alacritty/catppuccin-frappe.toml"
  # "~/.config/alacritty/catppuccin-macchiato.toml"
  "~/.config/alacritty/catppuccin-mocha.toml"
]

[env]
TERM = "xterm-256color"

[window]
dynamic_padding = false
decorations = "buttonless"
startup_mode = "windowed"
opacity = 1

  [window.dimensions]
  columns = 100
  lines = 85

  [window.padding]
  x = 6
  y = 0

[scrolling]
history=5000

[font]
size = 18
# use_thin_strokes= true
  [font.normal]
  family = "JetBrainsMono Nerd Font"
  style = "Light"

  [font.bold]
  family = "JetBrainsMono Nerd Font"
  style = "Bold"

  [font.italic]
  family = "JetBrainsMono Nerd Font"

  style = "Italic"

  [font.offset]
  x = 0
  y = 0

  [font.glyph_offset]
  x = 0
  y = 0
